### ISSUE TITLE
TypeError: cannot astype a timedelta from [timedelta64[ns]] to [int32]

### ISSUE THREAD

**Issue by andymancodes** [facebook/prophet#593]
Hi,

while trying to run: fig = plot_cross_validation_metric(df_cv, metric='mape')

I am getting:

TypeError                                 Traceback (most recent call last)
<ipython-input-16-0861b7777af9> in <module>()
----> 1 fig = plot_cross_validation_metric(df_cv, metric='mape')

C:\Program Files\Anaconda3\envs\py35\lib\site-packages\fbprophet\plot.py in plot_cross_validation_metric(df_cv, metric, rolling_window, ax)
    462             break
    463 
--> 464     x_plt = df_none['horizon'].astype('timedelta64[ns]').astype(int) / float(dt_conversions[i])
    465     x_plt_h = df_h['horizon'].astype('timedelta64[ns]').astype(int) / float(dt_conversions[i])
    466 

C:\Program Files\Anaconda3\envs\py35\lib\site-packages\pandas\util\_decorators.py in wrapper(*args, **kwargs)
    176                 else:
    177                     kwargs[new_arg_name] = new_arg_value
--> 178             return func(*args, **kwargs)
    179         return wrapper
    180     return _deprecate_kwarg

C:\Program Files\Anaconda3\envs\py35\lib\site-packages\pandas\core\generic.py in astype(self, dtype, copy, errors, **kwargs)
   4995             # else, only a single dtype is given
   4996             new_data = self._data.astype(dtype=dtype, copy=copy, errors=errors,
-> 4997                                          **kwargs)
   4998             return self._constructor(new_data).__finalize__(self)
   4999 

C:\Program Files\Anaconda3\envs\py35\lib\site-packages\pandas\core\internals.py in astype(self, dtype, **kwargs)
   3712 
   3713     def astype(self, dtype, **kwargs):
-> 3714         return self.apply('astype', dtype=dtype, **kwargs)
   3715 
   3716     def convert(self, **kwargs):

C:\Program Files\Anaconda3\envs\py35\lib\site-packages\pandas\core\internals.py in apply(self, f, axes, filter, do_integrity_check, consolidate, **kwargs)
   3579 
   3580             kwargs['mgr'] = self
-> 3581             applied = getattr(b, f)(**kwargs)
   3582             result_blocks = _extend_blocks(applied, result_blocks)
   3583 

C:\Program Files\Anaconda3\envs\py35\lib\site-packages\pandas\core\internals.py in astype(self, dtype, copy, errors, values, **kwargs)
    573     def astype(self, dtype, copy=False, errors='raise', values=None, **kwargs):
    574         return self._astype(dtype, copy=copy, errors=errors, values=values,
--> 575                             **kwargs)
    576 
    577     def _astype(self, dtype, copy=False, errors='raise', values=None,

C:\Program Files\Anaconda3\envs\py35\lib\site-packages\pandas\core\internals.py in _astype(self, dtype, copy, errors, values, klass, mgr, **kwargs)
    662 
    663                 # _astype_nansafe works fine with 1-d only
--> 664                 values = astype_nansafe(values.ravel(), dtype, copy=True)
    665                 values = values.reshape(self.shape)
    666 

C:\Program Files\Anaconda3\envs\py35\lib\site-packages\pandas\core\dtypes\cast.py in astype_nansafe(arr, dtype, copy)
    694         raise TypeError("cannot astype a timedelta from [{from_dtype}] "
    695                         "to [{to_dtype}]".format(from_dtype=arr.dtype,
--> 696                                                  to_dtype=dtype))
    697 
    698     elif (np.issubdtype(arr.dtype, np.floating) and

TypeError: cannot astype a timedelta from [timedelta64[ns]] to [int32]

While,  df_p = performance_metrics(df_cv) works perfectly fine.

I really need to plot the error.

**Comment by FGGsysu** [comment]
Hi, @andymancodes  the exactly same 'TypeError' appeared when I ran the same code. So if you just want  to plot the error, maybe you could try to plot it with pd.DataFrame.plot(), it's not as pretty as the 'original ' output figure, but it work. May this would help.

**Comment by andymancodes** [comment]
@FGGsysu Hi, I am not getting how the evaluation of the model is goining on.

I have set my horizon to 30 days, yet I get

I get:

	horizon	mape
0	30	0.247988

  | horizon | mse | rmse | mae | mape | coverage
-- | -- | -- | -- | -- | -- | --
3 days 01:00:00 | 1.196251 | 1.093733 | 0.808108 | 0.189526 | 0.929949
3 days 01:00:00 | 1.196157 | 1.093690 | 0.807951 | 0.189485 | 0.929949
3 days 01:00:00 | 1.192805 | 1.092156 | 0.806375 | 0.189264 | 0.929949
3 days 01:00:00 | 1.194557 | 1.092958 | 0.807047 | 0.189117 | 0.929949
3 days 01:30:00 | 1.194866 | 1.093099 | 0.807151 | 0.188838 | 0.929949

How to plot the error now? What does it mean? Any help would be wonderful! Thanks.

**Comment by bletham** [comment]
This is a bug that shows up on 32-bit systems (see also #591). It was fixed in #577, but the fix hasn't been pushed to PyPI yet. In the meantime you can download and install the current github version.

**Comment by bletham** [comment]
I'm going to leave this open until we push the next version to pip which will have this fix.

**Comment by eromoe** [comment]
@bletham  32-bit system ? I don't understand,  my env as below got this error too .

python is 64bit: 
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32

system is x64:
![image](https://user-images.githubusercontent.com/3938751/49569506-18596d00-f96f-11e8-81c9-4374c44644c4.png)

**Comment by ajoros** [comment]
I have latest fbprophet package and I am having this issue as well, and I am on 64-bit system. I even manually went into plot.py and modified lines 464 and 465 to use .astype(np.int64) , and still no luck. Error continues saying:
"cannot astype a timedelta from[timedelta64[ns]] to [int32]"

**Comment by ajoros** [comment]
Solved: I updated PyStan to 2.18.0.0 manually using conda install pystan=2.18.0.0 ... conda-forge still uses 2.17.1.0 which was the root of the problem. PyStan update was needed.

**Comment by bletham** [comment]
@ajoros we just pushed a new version (0.4) to PyPI that should fix this. Could you re-install fbprophet and check if it works now?
```
pip uninstall fbprophet
pip install fbprophet --no-cache-dir --no-binary :all:
```

**Comment by bletham** [comment]
The fix has been pushed to PyPI so I'll close this, but @ajoros keep me posted so we can make sure it is working in your case.
